<?php
/**
 * output Gigya registration form html.
 * defined in GigyaIM\view\frontend\layout\customer_account_create.xml
 * The block for this form is - GigyaIM\Block\Form\GigyaRegister.php
 *
 * Here: add accounts.showScreenSet to gigyaInit array
 * Full flow (on gigya_script):
 * Call gigya screen sets.
 * Capture Gigya login event.
 * Create and submit registration form.
 * Submit to Gigya model Controller.
**/

/** @var \Gigya\GigyaIM\Block\Form\GigyaRegister $block */
?>

<div id="gigya-register" class="gigya-register gigya-loader-location"></div>
<script>
    window.gigyaInit = window.gigyaInit || [];
    var screenSetParams = {
        screenSet : "<?php echo $block->getLoginDesktopScreensetId() ?>",
        containerID : "gigya-register",
        startScreen : "gigya-register-screen",
        mobileScreenSet : "<?php echo $block->getLoginMobileScreensetId() ?>", // optional - for using separate mobile screen set.
		include : 'id_token'
    };
    var raasRegisterScreen = {"function": "accounts.showScreenSet", "parameters": screenSetParams};
    window.gigyaInit.push(raasRegisterScreen);
</script>
