<?php
/**
 * output Gigya login form html.
 * defined in GigyaIM\view\frontend\layout\customer_account_login.xml
 * The block for this form is - GigyaIM\Block\Form\Gigyalogin.php
 *
 * Here: add accounts.showScreenSet to gigyaInit array
 * Full flow (on gigya_script):
 * Call gigya screen sets.
 * Capture Gigya login event.
 * Create and submit registration form.
 * Submit to Gigya model Controller.
 **/

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Login $block */
?>
<?php
/**
 * Customer login form template
 *
 * @see \Magento\Customer\Block\Form\Login
 * @var $block \Magento\Customer\Block\Form\Login
 */
?>
<div class="block block-customer-login">
    <div class="block-title">
        <strong id="block-customer-login-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo __('Registered Customers') ?></strong>
    </div>
    <div class="block-content" aria-labelledby="block-customer-login-heading">
        <!-- Gigya login screen placeholder - id can be dynamic: -->
        <div id="gigya-login" class="gigya-login"></div>
        <?php echo $block->getBlockHtml('formkey'); ?>
        <script>
            // add Raas login screens function to Gigya init.
            window.gigyaInit = window.gigyaInit || [];
            var screenSetParams = {
                screenSet : "Default-RegistrationLogin",
                containerID : "gigya-login",
                startScreen : "gigya-login-screen",
                mobileScreenSet : "" // optional - for using separate mobile screen set.
            };
            var raasLoginScreen = {"function": "accounts.showScreenSet", "parameters": screenSetParams};
            window.gigyaInit.push(raasLoginScreen);
        </script>
    </div>
</div>
