<?php
/**
 * Output Gigya login form html.
 * defined in GigyaIM\view\frontend\layout\customer_account_login.xml
 * The block for this form is - GigyaIM\Block\Form\Gigyalogin which is mapped to Magento Customer block. mapped in di.xml
 *
 * Here: add accounts.showScreenSet to gigyaInit array
 * Full flow (on gigya_script):
 * Call gigya screen sets.
 * Capture Gigya login event.
 * Create and submit registration form.
 * Submit to Gigya model Controller.
 **/

/** @var \Gigya\GigyaIM\Block\Form\GigyaLogin $block */
?>

<?php
// check display type from xml. set container div class and login div id to match
$display = $block->getData('display'); // popup /embed
$id = 'gigya-login-popup';
if ($display === 'embed') {
    $id = 'gigya-login-embed';
}
?>
<div class="block block-customer-login">
    <div class="block-content" aria-labelledby="block-customer-login-heading">
        <!-- Gigya login screen placeholder - id can be dynamic: -->
        <div id="<?php echo $id; ?>" class="gigya-login gigya-loader-location"></div>
        <?php echo $block->getBlockHtml('formkey'); ?>
        <script>
            // add Raas login screens function to Gigya init.
            window.gigyaInit = window.gigyaInit || [];
            var screenSetParams = {
                screenSet : "<?php echo $block->getLoginDesktopScreensetId() ?>",
                containerID : "<?php echo $id; ?>",
                startScreen : "gigya-login-screen",
                mobileScreenSet : "<?php echo $block->getLoginMobileScreensetId() ?>" // optional - for using separate mobile screen set.
            };
            var raasLoginScreen = {"function": "accounts.showScreenSet", "parameters": screenSetParams};
            window.gigyaInit.push(raasLoginScreen);
        </script>
    </div>
</div>
