<?php
/*
 * Add Gigya script to page body.
 * Defined in view/frontend/layout/default.xml
 * Variables can be set and passed from the block object model: block/GigyaScript
 * Alan storm : http://alanstorm.com/magento-2-frontend-files-serving
 */

$api_key = $block->getGigyaApiKey();
$site = $block->getBaseUrl();
 //$login_action_url = $site . "gigya_raas/raas/gigyapost";
$login_action_url = $block->getPostActionUrl();

$magento_user_logged_in = $block->getMagentoUserLogin();
$gigya_user_logged_in = $block->getGigyaUserLogin();
?>

<script>
    var success_url = "";   // will be added from gigya admin
    var error_url = "";     // will be added from gigya admin
    var dummy_password = "12qwaszx!@QWASZX"; // placeholder password

    function loadGigyaScript() {
        var gig = document.createElement('script');
        gig.type = 'text/javascript';
        gig.async = false;
        gig.src = ('https:' == document.location.protocol ? 'https://cdns' : 'http://cdn') + '.gigya.com/js/gigya.js?apiKey=<?php echo $api_key ?>';
        document.getElementsByTagName('head')[0].appendChild(gig);
    }
    loadGigyaScript();

    /////////////////////////////////

    gigyaMage2 = {};
    gigyaMage2.Params = {};
    gigyaMage2.Functions = {};
    window.gigyaInit = window.gigyaInit || [];

    /**
     * Login event handler. set parameters for magento form submission
     * @param eventObj
     */
    gigyaMage2.Functions.gigyaLoginEventHandler = function(eventObj) {
        var action = "<?php  echo $login_action_url; ?>";

        var loginData = {
            UIDSignature : eventObj.UIDSignature,
            signatureTimestamp : eventObj.signatureTimestamp,
            UID : eventObj.UID
        };
        gigyaMage2.Functions.gigyaSubmitLoginRegister(action, loginData, eventObj );
    };

    /**
     * Submit form after capturing Gigya login event. used for Login & Registration
     * @param action
     * @param loginData
     * @param eventObj
     */
    gigyaMage2.Functions.gigyaSubmitLoginRegister = function (action, loginData, eventObj) {
        var form = gigyaMage2.Functions.gigyaFormCreate(action);

        gigyaMage2.Functions.createInputField("login_data", JSON.stringify(loginData), form);

        // Login form placeholder
        gigyaMage2.Functions.createInputField("login[]", "", form);

        // Registration
        gigyaMage2.Functions.createInputField("success_url", success_url, form);
        gigyaMage2.Functions.createInputField("error_url", error_url, form);
        gigyaMage2.Functions.createInputField("firstname", eventObj.profile.firstname, form);
        gigyaMage2.Functions.createInputField("lastname", eventObj.profile.lastname, form);
        gigyaMage2.Functions.createInputField("password", dummy_password, form);
        gigyaMage2.Functions.createInputField("password_confirmation", dummy_password, form);

        gigyaMage2.Functions.gigyaFormSubmit(form);
    };

    /**
     * Append form to body and submit
     * @param form
     */
    gigyaMage2.Functions.gigyaFormSubmit = function(form) {
        form.appendTo('body');
        form.submit();
    };

    /**
     * Create form DOM element with form key
     * @param action
     * @returns form
     */
    gigyaMage2.Functions.gigyaFormCreate = function(action) {
        'use strict';
        var form;
        form = jQuery('<form />', {
            action: action,
            method: "POST",
            style: 'display: none;'
        });
        // add form key if it exists
        if ( jQuery('input[name="form_key"]').val().length ){
            var form_key = jQuery('input[name="form_key"]').val();
            gigyaMage2.Functions.createInputField("form_key", form_key, form);
        }
        return form;
    };

    /**
     * Create Input field
     * @param name
     * @param value
     * @param form
     */
    gigyaMage2.Functions.createInputField = function (name, value, form) {
        jQuery('<input>').attr({
            type: 'hidden',
            name: name,
            value: value
        }).appendTo(form);
    };

    /**
     * Create and Submit update profile form
     * @param eventObj
     */
    gigyaMage2.Functions.gigyaUpdateProfile = function(eventObj) {
        var action = "<?php echo $block->getUrl('customer/account/editPost') ?>";
        var form = gigyaMage2.Functions.gigyaFormCreate(action);
        gigyaMage2.Functions.createInputField( "email", eventObj.profile.email , form);
        gigyaMage2.Functions.createInputField( "firstname", eventObj.profile.firstName , form);
        gigyaMage2.Functions.createInputField( "lastname", eventObj.profile.lastName , form);
        gigyaMage2.Functions.gigyaFormSubmit(form);
    };

    // init registered Gigya functions
    function onGigyaServiceReady(serviceName) {
        if (window.gigyaInit) {
            // If this is the edit profile page, then add the update profile callback function.
            if( window.gigyaInit[0].parameters.containerID == "gigya-edit-profile") {
                window.gigyaInit[0].parameters.onAfterSubmit = gigyaMage2.Functions.gigyaUpdateProfile;
            }
            var length = window.gigyaInit.length,
                element = null;
            if (length > 0) {
                for (var i = 0; i < length; i++) {
                    element = window.gigyaInit[i];
                    func = element.function;
                    var parts = func.split("\.");
                    var f = gigya[parts[0]][parts[1]];
                    if (typeof f === "function") {
                        f(element.parameters);
                    }
                }
            }

            gigya.accounts.addEventHandlers(
                {
                    onLogin: gigyaMage2.Functions.gigyaLoginEventHandler,
                    onAfterSubmit : gigyaMage2.Functions.gigyaUpdateProfile
                }
            )
        }
    }

    // If Magento login failed, logout Gigya
    var magento_user_logged_in = <?php echo $magento_user_logged_in ?>;
    var gigya_user_logged_in = <?php echo $gigya_user_logged_in ?>;
    if (gigya_user_logged_in && !magento_user_logged_in )  {
        var logoutSync = {"function": "accounts.logout", "parameters": {} };
        window.gigyaInit.push(logoutSync);
    }

</script>
<script>
    // Capture Magento logout and log out gigya
    require([
        "jquery"
    ], function($) {
        "use strict";
        $('a[href$="logout/"]').click(function () {
            gigya.accounts.logout();
            return true;
        });
    });
</script>
<?php
/*
// Gigya Post minimal:
// $_POST = {array} [11]
    // eventName = "login"
    // remember = "false"
    // provider = "facebook"
    // loginMode = "standard"
    // newUser = "false"
    // UIDSignature = "o/Esfdi+0Y5Q16h8JyZ4NJH9P9g="
    // signatureTimestamp = "1450341234"
    // UID = "_guid_PpabVRL9jSl1I1fp151zFHFSc08FOWLKH6IJ3WQqcMw="
    // profile = {array} [7]
        //  firstName = "Guy"
        //  lastName = "Gigi"
        //  photoURL = "https://graph.facebook.com/v2.3/100008758338831/picture?type=large"
        //  thumbnailURL = "https://graph.facebook.com/v2.3/100008758338831/picture?type=square"
        //  profileURL = "https://www.facebook.com/app_scoped_user_id/100008758338831/"
        //  gender = "m"
        //  email = "gigguy191@gmail.com"
    // isGlobal = "true"
    // source = "showScreenSet"
*/
?>