<?php
/*
 * Add Gigya script to page body.
 * Defined in view/frontend/layout/default.xml
 * Variables can be set and passed from the block object model: block/GigyaScript
 */

?>

<script>
var login_state_url = "<?php echo $block->getMagentoLoginStateUrl() ?>";
var logout_url = "<?php echo $block->getLogoutUrl() ?>";
var login_post_url = "<?php echo $block->getPostActionUrl(); ?>";
var edit_post_url = "<?php echo $block->getUrl('customer/account/editPost') ?>";
var allow_gigya_logout = <?php echo $block->getAllowGigyaLogout() ?>;
var login_url = "<?php echo $block->getLoginUrl() ?>";
var magento_user_logged_in = false;

    var m;
</script>

<script>

    require([
        "jquery",
        "gigya_script"
    ], function($, gigyaMage2){
        m = gigyaMage2;
        "use strict";
        $.ajax({
            type : "GET",
            url : login_state_url,
            showLoader: false
        })
        .done(function(data) {
            if(typeof data.logged_in != 'undefined')
            {
                magento_user_logged_in = (data.logged_in == '1');
                gigyaMage2.Params.magento_user_logged_in = magento_user_logged_in;
            }

            window.gigyaInit = window.gigyaInit || [];
            // Set Gigya global configuration object
            window.__gigyaConf = {
                // Gigya user session time should be equal to Magento session time
                sessionExpiration: <?php echo $block->getUserSessionLifetime(); ?>
            };

            gigyaMage2.Functions.loadGigyaScript(
                "<?php echo $block->getGigyaApiKey() ?>",
                "<?php echo $block->getLanguage() ?>"
            );

            // Session synchronization between Gigya and Magento
            gigyaMage2.Functions.syncSessionStatus();

            $('a[href$="logout/"]').click(function () {
                gigya.accounts.logout();
                return true;
            });

        });
    });

</script>
