<?php
$element_id = $block->getData('element_id'); // popup /embed
$display = $block->getData('display'); // popup /embed
$id = ($display == 'embed') ? 'gigya-screenset-'.$element_id.'-embed' : 'gigya-screenset-'.$element_id.'-popup';
?>
<div class="block block-screenset-<?php echo $element_id; ?>">
	<div class="block-content" aria-labelledby="block-<?php echo $element_id; ?>-heading">
		<!-- Gigya login screen placeholder - id can be dynamic: -->
		<div id="<?php echo $id; ?>" class="gigya-screenset gigya-loader-location"></div>
		<script>
			window.gigyaInit = window.gigyaInit || [];
			var screenSetParams = {
				screenSet : "<?php echo $block->getData('desktop'); ?>",
				containerID : "<?php echo $id; ?>",
				startScreen : "gigya-login-screen",
				mobileScreenSet : "<?php echo $block->getData('mobile'); ?>" // optional - for using separate mobile screen set.
			};
			var screenSet_<?php echo $element_id; ?> = {"function": "accounts.showScreenSet", "parameters": screenSetParams};
			window.gigyaInit.push(screenSet_<?php echo $element_id; ?>);
		</script>
	</div>
</div>