<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Account\Dashboard\Info $block */

?>
<div class="block block-dashboard-info">
    <div class="block-title"><strong><?php /* @escapeNotVerified */ echo __('Account Information') ?></strong></div>
    <div class="block-content">
        <div id="gigya-edit-profile" class="gigya-edit-profile gigya-loader-location"></div>
        <?php echo $block->getBlockHtml('formkey'); ?>
        <script>
            window.gigyaInit = window.gigyaInit || [];
            var screenSetParams = {
                screenSet : "Default-ProfileUpdate",
                containerID : "gigya-edit-profile",
                mobileScreenSet : "" // optional - for using separate mobile screen set.
            };
            var raasInfoScreen = {"function": "accounts.showScreenSet", "parameters": screenSetParams};
            window.gigyaInit.push(raasInfoScreen);
        </script>
    </div>
</div>
